### ISSUE TITLE
CSS style 적용 방법 및 ClassName naming convention 결정

### ISSUE THREAD

**Issue by grcenneat** [WinterSpringProject/PROJECT-PIND-FE#14]
> 리액트에서 CSS 스타일을 적용하는 방법은 대표적으로 4가지가 있습니다.
> 각각의 방법을 비교해보고 저희 프로젝트에 가장 적합한 방법을 선택한 과정을 정리합니다.

### 1. 가장 흔한 방식, 일반 CSS
 - ClassName 기반.
 - `.css` 파일을 따로 만들어서 사용
 - ClassName은 컴포넌트이름-클래스 형태로 지어라
 - CSS Selector
   - 컴포넌트의 최상위 html 요소에는 컴포넌트의 이름으로 클래스명(.App)을 짓고, 그 내부에서는 소문자로 클래스명(.logo)을 만들거나 태그를 이용해 클래스명을 아예 생략하는 방식도 있다.

### 2. Sass (Syntactically Awesome Style Sheets)
 - CSS 전처리기로 복잡한 작업을 쉽게 할 수 있게 해주고, 스타일 코드의 재활용성, 가독성을 높인 방법
   - 변수와 `@mixin`, 상위선택자 참조(`&`)등을 사용할 수 있다.
   - 라이브러리를 쉽게 불러와서 사용할 수 있다.
 - Sass 에선 `.scss` 와 `.sass` 확장자를 지원한다. `scss`가 더 일반적으로 쓰인다.
 - `node-sass` 라이브러리를 설치해야함. (Sass -> CSS 로 변환해주는 라이브러리)

### 3. CSS Module
- CSS를 불러와서 사용할 때 클래스 이름을 고유한 값, 즉 `[파일이름]_[클래스 이름]__[해시값]` 형태로 자동으로 만들어서 컴포넌트 스타일 클래스 이름이 중첩되는 것을 방지해주는 기술.
- 템플릿 리터럴을 이용해 css style들을 모듈처럼 사용
- `.modules.css` 확장자 사용
- `:global` 키워드
- className이라는 라이브러리가 있는데 이를 이용하면 CSS 클래스를 조건부로 설정할 때 유용하다. Sass와 함께 사용하는 것도 가능.

### 4. styled-components
- 컴포넌트 js 파일 내부에 CSS를 같이 선언하는 방법.
- `styled-components` 라이브러리 설치해야함.
- css 파일을 따로 만들지 않아도 된다는 장점이 있다.
- props로 전달해주는 값을 쉽게 스타일에 적용할 수 있다는 장점 덕에 조건부 스타일링도 쉬움. (tagged 템플릿 리터럴 사용)
- 리액트에서만 사용할 수 있는 방법

* * *
### 논의
- 컴포넌트 각각에 CSS를 쓰는 것이 가장 일반적이긴 하다.
- 하나의 큰 CSS 파일을 만드는 것은 가독성이 떨어지고, 관리하기도 어렵고, 분명히 확장성에도 한계가 있다.
- SASS는 좋은 방법이지만 SASS를 새로 익히는 시간이 들어갑니다. SASS를 활용해 모듈을 잘 분리해서 쓰면 깔끔한 코드가 될 것 같음.
- CSS Module은 복잡하다.
- Styled-component도 복잡하다. js 파일 안에 css까지 있는게 오히려 깔끔하지 않아보일 수 있고, 필요 이상의 코드를 작성해야 할수도.

* * *
### => scss 사용
+ 라이브러리를 쉽게 가져와서 사용할 수 있고, 코드를 깔끔하게 관리할 수 있다는 장점 때문에 선택.
+ CSS Module과 styled-components는 익숙하지 않고, 새로 익혀야할 것들이 너무 많은 것 같다.
+ 추후에 도입을 할수도 안할수도 있지만 활용해보고 싶은 sass 기능 
  - 자주 쓰는 변수와 @mixin 파일 분리해 @import로 불러와서 사용
  - classname 모듈을 import해 scss에서 조건부 스타일로 사용

 ### 클래스명 네이밍 규칙
  - 컴포넌트의 최상위 요소에 컴포넌트 이름으로 ClassName을 지정하고
  - 하위 요소들은 `컴포넌트명-클래스명`으로 하고
  - 제일 하위 요소에 대해서만 상위선택자(`&`) 참조할 수 있게 클래스네임을 하나 더 만들어준다.
  - 예시
  
```html
<div className="CardViewListItem">
  <div className="CardViewListItem-thumbnail">
    <img className="CardViewListItem-thumbnail img" src={logo} alt="" width="200" />
    <div className="CardViewListItem-thumbnail bookmark">
      {is_starred}
    </div>
  </div>
</div>
```

```scss
.CardViewListItem {
--shadow-color: #00000029;
box-shadow: 3px 3px 10px 0 var(--shadow-color);
transition: 0.3s;
width: 270px;
height: 411px;
border-radius: 31px;

  .CardViewListItem-thumbnail {
    position: relative;
    // CardViewListItem-thumbnail 이 img와 함께 사용되었을 경우
    &.img {
      background: gray;
      width: 270px;
      height: 277px;
      border-radius: 31px 31px 0 0;
    }

    &.bookmark {
      background: white;
      width: 36px;
      height: 36px;
      border-radius: 50%;
      backdrop-filter: blur(2px);
      -webkit-backdrop-filter: blur(2px);
      opacity: 31%;
      position: absolute;
      top: 0;
      right: 0;
    }
  }
}
```
